/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_gl2jni_JniShell */

#ifndef _Included_com_android_gl2jni_JniShell
#define _Included_com_android_gl2jni_JniShell
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_gl2jni_JniShell
 * Method:    initApp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_JniShell_initApp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_android_gl2jni_JniShell
 * Method:    pauseApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_JniShell_pauseApp
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_JniShell
 * Method:    resumeApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_JniShell_resumeApp
  (JNIEnv *, jclass);

/*
 * Class:     com_android_gl2jni_JniShell
 * Method:    mainLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_gl2jni_JniShell_mainLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
