
/*
 * Copyright (C) 2013 Google Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 *     * Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following disclaimer
 * in the documentation and/or other materials provided with the
 * distribution.
 *     * Neither the name of Google Inc. nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */


#ifndef CSSPropertyNames_h
#define CSSPropertyNames_h

#include "CSSParserMode.h"
#include "wtf/HashFunctions.h"
#include "wtf/HashTraits.h"
#include <string.h>

namespace WTF {
class AtomicString;
class String;
}

namespace WebCore {

enum CSSPropertyID {
    CSSPropertyInvalid = 0,
    CSSPropertyDisplay = 1,
    CSSPropertyWebkitAnimation = 2,
    CSSPropertyWebkitAnimationDelay = 3,
    CSSPropertyWebkitAnimationDirection = 4,
    CSSPropertyWebkitAnimationDuration = 5,
    CSSPropertyWebkitAnimationFillMode = 6,
    CSSPropertyWebkitAnimationIterationCount = 7,
    CSSPropertyWebkitAnimationName = 8,
    CSSPropertyWebkitAnimationPlayState = 9,
    CSSPropertyWebkitAnimationTimingFunction = 10,
    CSSPropertyAnimation = 11,
    CSSPropertyAnimationDelay = 12,
    CSSPropertyAnimationDirection = 13,
    CSSPropertyAnimationDuration = 14,
    CSSPropertyAnimationFillMode = 15,
    CSSPropertyAnimationIterationCount = 16,
    CSSPropertyAnimationName = 17,
    CSSPropertyAnimationPlayState = 18,
    CSSPropertyAnimationTimingFunction = 19,
    CSSPropertyWebkitTransition = 20,
    CSSPropertyWebkitTransitionDelay = 21,
    CSSPropertyWebkitTransitionDuration = 22,
    CSSPropertyWebkitTransitionProperty = 23,
    CSSPropertyWebkitTransitionTimingFunction = 24,
    CSSPropertyTransition = 25,
    CSSPropertyTransitionDelay = 26,
    CSSPropertyTransitionDuration = 27,
    CSSPropertyTransitionProperty = 28,
    CSSPropertyTransitionTimingFunction = 29,
    CSSPropertyColor = 30,
    CSSPropertyDirection = 31,
    CSSPropertyFont = 32,
    CSSPropertyFontFamily = 33,
    CSSPropertyFontKerning = 34,
    CSSPropertyFontSize = 35,
    CSSPropertyFontStyle = 36,
    CSSPropertyFontVariant = 37,
    CSSPropertyFontVariantLigatures = 38,
    CSSPropertyFontWeight = 39,
    CSSPropertyTextRendering = 40,
    CSSPropertyWebkitFontFeatureSettings = 41,
    CSSPropertyWebkitFontSmoothing = 42,
    CSSPropertyWebkitLocale = 43,
    CSSPropertyWebkitTextOrientation = 44,
    CSSPropertyWebkitWritingMode = 45,
    CSSPropertyZoom = 46,
    CSSPropertyLineHeight = 47,
    CSSPropertyBackground = 48,
    CSSPropertyBackgroundAttachment = 49,
    CSSPropertyBackgroundBlendMode = 50,
    CSSPropertyBackgroundClip = 51,
    CSSPropertyBackgroundColor = 52,
    CSSPropertyBackgroundImage = 53,
    CSSPropertyBackgroundOrigin = 54,
    CSSPropertyBackgroundPosition = 55,
    CSSPropertyBackgroundPositionX = 56,
    CSSPropertyBackgroundPositionY = 57,
    CSSPropertyBackgroundRepeat = 58,
    CSSPropertyBackgroundRepeatX = 59,
    CSSPropertyBackgroundRepeatY = 60,
    CSSPropertyBackgroundSize = 61,
    CSSPropertyBorder = 62,
    CSSPropertyBorderBottom = 63,
    CSSPropertyBorderBottomColor = 64,
    CSSPropertyBorderBottomLeftRadius = 65,
    CSSPropertyBorderBottomRightRadius = 66,
    CSSPropertyBorderBottomStyle = 67,
    CSSPropertyBorderBottomWidth = 68,
    CSSPropertyBorderCollapse = 69,
    CSSPropertyBorderColor = 70,
    CSSPropertyBorderImage = 71,
    CSSPropertyBorderImageOutset = 72,
    CSSPropertyBorderImageRepeat = 73,
    CSSPropertyBorderImageSlice = 74,
    CSSPropertyBorderImageSource = 75,
    CSSPropertyBorderImageWidth = 76,
    CSSPropertyBorderLeft = 77,
    CSSPropertyBorderLeftColor = 78,
    CSSPropertyBorderLeftStyle = 79,
    CSSPropertyBorderLeftWidth = 80,
    CSSPropertyBorderRadius = 81,
    CSSPropertyBorderRight = 82,
    CSSPropertyBorderRightColor = 83,
    CSSPropertyBorderRightStyle = 84,
    CSSPropertyBorderRightWidth = 85,
    CSSPropertyBorderSpacing = 86,
    CSSPropertyBorderStyle = 87,
    CSSPropertyBorderTop = 88,
    CSSPropertyBorderTopColor = 89,
    CSSPropertyBorderTopLeftRadius = 90,
    CSSPropertyBorderTopRightRadius = 91,
    CSSPropertyBorderTopStyle = 92,
    CSSPropertyBorderTopWidth = 93,
    CSSPropertyBorderWidth = 94,
    CSSPropertyBottom = 95,
    CSSPropertyBoxShadow = 96,
    CSSPropertyBoxSizing = 97,
    CSSPropertyCaptionSide = 98,
    CSSPropertyClear = 99,
    CSSPropertyClip = 100,
    CSSPropertyWebkitClipPath = 101,
    CSSPropertyContent = 102,
    CSSPropertyCounterIncrement = 103,
    CSSPropertyCounterReset = 104,
    CSSPropertyCursor = 105,
    CSSPropertyEmptyCells = 106,
    CSSPropertyFloat = 107,
    CSSPropertyFontStretch = 108,
    CSSPropertyHeight = 109,
    CSSPropertyImageRendering = 110,
    CSSPropertyIsolation = 111,
    CSSPropertyJustifySelf = 112,
    CSSPropertyLeft = 113,
    CSSPropertyLetterSpacing = 114,
    CSSPropertyListStyle = 115,
    CSSPropertyListStyleImage = 116,
    CSSPropertyListStylePosition = 117,
    CSSPropertyListStyleType = 118,
    CSSPropertyMargin = 119,
    CSSPropertyMarginBottom = 120,
    CSSPropertyMarginLeft = 121,
    CSSPropertyMarginRight = 122,
    CSSPropertyMarginTop = 123,
    CSSPropertyMaskSourceType = 124,
    CSSPropertyMaxHeight = 125,
    CSSPropertyMaxWidth = 126,
    CSSPropertyMinHeight = 127,
    CSSPropertyMinWidth = 128,
    CSSPropertyMixBlendMode = 129,
    CSSPropertyOpacity = 130,
    CSSPropertyOrphans = 131,
    CSSPropertyOutline = 132,
    CSSPropertyOutlineColor = 133,
    CSSPropertyOutlineOffset = 134,
    CSSPropertyOutlineStyle = 135,
    CSSPropertyOutlineWidth = 136,
    CSSPropertyObjectFit = 137,
    CSSPropertyObjectPosition = 138,
    CSSPropertyOverflow = 139,
    CSSPropertyOverflowWrap = 140,
    CSSPropertyOverflowX = 141,
    CSSPropertyOverflowY = 142,
    CSSPropertyPadding = 143,
    CSSPropertyPaddingBottom = 144,
    CSSPropertyPaddingLeft = 145,
    CSSPropertyPaddingRight = 146,
    CSSPropertyPaddingTop = 147,
    CSSPropertyPage = 148,
    CSSPropertyPageBreakAfter = 149,
    CSSPropertyPageBreakBefore = 150,
    CSSPropertyPageBreakInside = 151,
    CSSPropertyPointerEvents = 152,
    CSSPropertyPosition = 153,
    CSSPropertyQuotes = 154,
    CSSPropertyResize = 155,
    CSSPropertyRight = 156,
    CSSPropertyScrollBehavior = 157,
    CSSPropertySize = 158,
    CSSPropertySrc = 159,
    CSSPropertySpeak = 160,
    CSSPropertyTableLayout = 161,
    CSSPropertyTabSize = 162,
    CSSPropertyTextAlign = 163,
    CSSPropertyTextAlignLast = 164,
    CSSPropertyTextDecoration = 165,
    CSSPropertyTextDecorationLine = 166,
    CSSPropertyTextDecorationStyle = 167,
    CSSPropertyTextDecorationColor = 168,
    CSSPropertyTextIndent = 169,
    CSSPropertyTextJustify = 170,
    CSSPropertyTextLineThroughColor = 171,
    CSSPropertyTextLineThroughMode = 172,
    CSSPropertyTextLineThroughStyle = 173,
    CSSPropertyTextLineThroughWidth = 174,
    CSSPropertyTextOverflow = 175,
    CSSPropertyTextOverlineColor = 176,
    CSSPropertyTextOverlineMode = 177,
    CSSPropertyTextOverlineStyle = 178,
    CSSPropertyTextOverlineWidth = 179,
    CSSPropertyTextShadow = 180,
    CSSPropertyTextTransform = 181,
    CSSPropertyTextUnderlineColor = 182,
    CSSPropertyTextUnderlineMode = 183,
    CSSPropertyTextUnderlineStyle = 184,
    CSSPropertyTextUnderlineWidth = 185,
    CSSPropertyTextUnderlinePosition = 186,
    CSSPropertyTop = 187,
    CSSPropertyTouchAction = 188,
    CSSPropertyTouchActionDelay = 189,
    CSSPropertyUnicodeBidi = 190,
    CSSPropertyUnicodeRange = 191,
    CSSPropertyVerticalAlign = 192,
    CSSPropertyVisibility = 193,
    CSSPropertyWhiteSpace = 194,
    CSSPropertyWidows = 195,
    CSSPropertyWidth = 196,
    CSSPropertyWillChange = 197,
    CSSPropertyWordBreak = 198,
    CSSPropertyWordSpacing = 199,
    CSSPropertyWordWrap = 200,
    CSSPropertyZIndex = 201,
    CSSPropertyWebkitAppearance = 202,
    CSSPropertyWebkitAspectRatio = 203,
    CSSPropertyWebkitBackfaceVisibility = 204,
    CSSPropertyWebkitBackgroundClip = 205,
    CSSPropertyWebkitBackgroundComposite = 206,
    CSSPropertyWebkitBackgroundOrigin = 207,
    CSSPropertyWebkitBackgroundSize = 208,
    CSSPropertyWebkitBorderAfter = 209,
    CSSPropertyWebkitBorderAfterColor = 210,
    CSSPropertyWebkitBorderAfterStyle = 211,
    CSSPropertyWebkitBorderAfterWidth = 212,
    CSSPropertyWebkitBorderBefore = 213,
    CSSPropertyWebkitBorderBeforeColor = 214,
    CSSPropertyWebkitBorderBeforeStyle = 215,
    CSSPropertyWebkitBorderBeforeWidth = 216,
    CSSPropertyWebkitBorderEnd = 217,
    CSSPropertyWebkitBorderEndColor = 218,
    CSSPropertyWebkitBorderEndStyle = 219,
    CSSPropertyWebkitBorderEndWidth = 220,
    CSSPropertyWebkitBorderFit = 221,
    CSSPropertyWebkitBorderHorizontalSpacing = 222,
    CSSPropertyWebkitBorderImage = 223,
    CSSPropertyWebkitBorderRadius = 224,
    CSSPropertyWebkitBorderStart = 225,
    CSSPropertyWebkitBorderStartColor = 226,
    CSSPropertyWebkitBorderStartStyle = 227,
    CSSPropertyWebkitBorderStartWidth = 228,
    CSSPropertyWebkitBorderVerticalSpacing = 229,
    CSSPropertyWebkitBoxAlign = 230,
    CSSPropertyWebkitBoxDirection = 231,
    CSSPropertyWebkitBoxFlex = 232,
    CSSPropertyWebkitBoxFlexGroup = 233,
    CSSPropertyWebkitBoxLines = 234,
    CSSPropertyWebkitBoxOrdinalGroup = 235,
    CSSPropertyWebkitBoxOrient = 236,
    CSSPropertyWebkitBoxPack = 237,
    CSSPropertyWebkitBoxReflect = 238,
    CSSPropertyWebkitBoxShadow = 239,
    CSSPropertyInternalCallback = 240,
    CSSPropertyWebkitColumnAxis = 241,
    CSSPropertyWebkitColumnBreakAfter = 242,
    CSSPropertyWebkitColumnBreakBefore = 243,
    CSSPropertyWebkitColumnBreakInside = 244,
    CSSPropertyWebkitColumnCount = 245,
    CSSPropertyColumnFill = 246,
    CSSPropertyWebkitColumnGap = 247,
    CSSPropertyWebkitColumnProgression = 248,
    CSSPropertyWebkitColumnRule = 249,
    CSSPropertyWebkitColumnRuleColor = 250,
    CSSPropertyWebkitColumnRuleStyle = 251,
    CSSPropertyWebkitColumnRuleWidth = 252,
    CSSPropertyWebkitColumnSpan = 253,
    CSSPropertyWebkitColumnWidth = 254,
    CSSPropertyWebkitColumns = 255,
    CSSPropertyWebkitBoxDecorationBreak = 256,
    CSSPropertyWebkitFilter = 257,
    CSSPropertyAlignContent = 258,
    CSSPropertyAlignItems = 259,
    CSSPropertyAlignSelf = 260,
    CSSPropertyFlex = 261,
    CSSPropertyFlexBasis = 262,
    CSSPropertyFlexDirection = 263,
    CSSPropertyFlexFlow = 264,
    CSSPropertyFlexGrow = 265,
    CSSPropertyFlexShrink = 266,
    CSSPropertyFlexWrap = 267,
    CSSPropertyJustifyContent = 268,
    CSSPropertyWebkitFontSizeDelta = 269,
    CSSPropertyGridAutoColumns = 270,
    CSSPropertyGridAutoFlow = 271,
    CSSPropertyGridAutoRows = 272,
    CSSPropertyGridArea = 273,
    CSSPropertyGridColumn = 274,
    CSSPropertyGridColumnEnd = 275,
    CSSPropertyGridColumnStart = 276,
    CSSPropertyGridTemplateColumns = 277,
    CSSPropertyGridTemplateRows = 278,
    CSSPropertyGridRow = 279,
    CSSPropertyGridRowEnd = 280,
    CSSPropertyGridRowStart = 281,
    CSSPropertyGridTemplateAreas = 282,
    CSSPropertyWebkitHighlight = 283,
    CSSPropertyWebkitHyphenateCharacter = 284,
    CSSPropertyWebkitLineBoxContain = 285,
    CSSPropertyWebkitLineBreak = 286,
    CSSPropertyWebkitLineClamp = 287,
    CSSPropertyWebkitLogicalWidth = 288,
    CSSPropertyWebkitLogicalHeight = 289,
    CSSPropertyWebkitMarginAfterCollapse = 290,
    CSSPropertyWebkitMarginBeforeCollapse = 291,
    CSSPropertyWebkitMarginBottomCollapse = 292,
    CSSPropertyWebkitMarginTopCollapse = 293,
    CSSPropertyWebkitMarginCollapse = 294,
    CSSPropertyWebkitMarginAfter = 295,
    CSSPropertyWebkitMarginBefore = 296,
    CSSPropertyWebkitMarginEnd = 297,
    CSSPropertyWebkitMarginStart = 298,
    CSSPropertyWebkitMask = 299,
    CSSPropertyWebkitMaskBoxImage = 300,
    CSSPropertyWebkitMaskBoxImageOutset = 301,
    CSSPropertyWebkitMaskBoxImageRepeat = 302,
    CSSPropertyWebkitMaskBoxImageSlice = 303,
    CSSPropertyWebkitMaskBoxImageSource = 304,
    CSSPropertyWebkitMaskBoxImageWidth = 305,
    CSSPropertyWebkitMaskClip = 306,
    CSSPropertyWebkitMaskComposite = 307,
    CSSPropertyWebkitMaskImage = 308,
    CSSPropertyWebkitMaskOrigin = 309,
    CSSPropertyWebkitMaskPosition = 310,
    CSSPropertyWebkitMaskPositionX = 311,
    CSSPropertyWebkitMaskPositionY = 312,
    CSSPropertyWebkitMaskRepeat = 313,
    CSSPropertyWebkitMaskRepeatX = 314,
    CSSPropertyWebkitMaskRepeatY = 315,
    CSSPropertyWebkitMaskSize = 316,
    CSSPropertyWebkitMaxLogicalWidth = 317,
    CSSPropertyWebkitMaxLogicalHeight = 318,
    CSSPropertyWebkitMinLogicalWidth = 319,
    CSSPropertyWebkitMinLogicalHeight = 320,
    CSSPropertyOrder = 321,
    CSSPropertyWebkitPaddingAfter = 322,
    CSSPropertyWebkitPaddingBefore = 323,
    CSSPropertyWebkitPaddingEnd = 324,
    CSSPropertyWebkitPaddingStart = 325,
    CSSPropertyWebkitPerspective = 326,
    CSSPropertyWebkitPerspectiveOrigin = 327,
    CSSPropertyWebkitPerspectiveOriginX = 328,
    CSSPropertyWebkitPerspectiveOriginY = 329,
    CSSPropertyWebkitPrintColorAdjust = 330,
    CSSPropertyWebkitRtlOrdering = 331,
    CSSPropertyWebkitRubyPosition = 332,
    CSSPropertyWebkitTextCombine = 333,
    CSSPropertyWebkitTextDecorationsInEffect = 334,
    CSSPropertyWebkitTextEmphasis = 335,
    CSSPropertyWebkitTextEmphasisColor = 336,
    CSSPropertyWebkitTextEmphasisPosition = 337,
    CSSPropertyWebkitTextEmphasisStyle = 338,
    CSSPropertyWebkitTextFillColor = 339,
    CSSPropertyWebkitTextSecurity = 340,
    CSSPropertyWebkitTextStroke = 341,
    CSSPropertyWebkitTextStrokeColor = 342,
    CSSPropertyWebkitTextStrokeWidth = 343,
    CSSPropertyWebkitTransform = 344,
    CSSPropertyWebkitTransformOrigin = 345,
    CSSPropertyWebkitTransformOriginX = 346,
    CSSPropertyWebkitTransformOriginY = 347,
    CSSPropertyWebkitTransformOriginZ = 348,
    CSSPropertyWebkitTransformStyle = 349,
    CSSPropertyWebkitUserDrag = 350,
    CSSPropertyWebkitUserModify = 351,
    CSSPropertyWebkitUserSelect = 352,
    CSSPropertyShapeInside = 353,
    CSSPropertyShapeOutside = 354,
    CSSPropertyShapeMargin = 355,
    CSSPropertyShapePadding = 356,
    CSSPropertyShapeImageThreshold = 357,
    CSSPropertyWebkitWrapFlow = 358,
    CSSPropertyWebkitWrapThrough = 359,
    CSSPropertyMaxZoom = 360,
    CSSPropertyMinZoom = 361,
    CSSPropertyOrientation = 362,
    CSSPropertyUserZoom = 363,
    CSSPropertyWebkitTapHighlightColor = 364,
    CSSPropertyWebkitAppRegion = 365,
    CSSPropertyInternalMarqueeDirection = 366,
    CSSPropertyInternalMarqueeIncrement = 367,
    CSSPropertyInternalMarqueeRepetition = 368,
    CSSPropertyInternalMarqueeSpeed = 369,
    CSSPropertyInternalMarqueeStyle = 370,
    CSSPropertyBufferedRendering = 371,
    CSSPropertyClipPath = 372,
    CSSPropertyClipRule = 373,
    CSSPropertyMask = 374,
    CSSPropertyEnableBackground = 375,
    CSSPropertyFilter = 376,
    CSSPropertyFloodColor = 377,
    CSSPropertyFloodOpacity = 378,
    CSSPropertyLightingColor = 379,
    CSSPropertyStopColor = 380,
    CSSPropertyStopOpacity = 381,
    CSSPropertyColorInterpolation = 382,
    CSSPropertyColorInterpolationFilters = 383,
    CSSPropertyColorProfile = 384,
    CSSPropertyColorRendering = 385,
    CSSPropertyFill = 386,
    CSSPropertyFillOpacity = 387,
    CSSPropertyFillRule = 388,
    CSSPropertyMarker = 389,
    CSSPropertyMarkerEnd = 390,
    CSSPropertyMarkerMid = 391,
    CSSPropertyMarkerStart = 392,
    CSSPropertyMaskType = 393,
    CSSPropertyShapeRendering = 394,
    CSSPropertyStroke = 395,
    CSSPropertyStrokeDasharray = 396,
    CSSPropertyStrokeDashoffset = 397,
    CSSPropertyStrokeLinecap = 398,
    CSSPropertyStrokeLinejoin = 399,
    CSSPropertyStrokeMiterlimit = 400,
    CSSPropertyStrokeOpacity = 401,
    CSSPropertyStrokeWidth = 402,
    CSSPropertyAlignmentBaseline = 403,
    CSSPropertyBaselineShift = 404,
    CSSPropertyDominantBaseline = 405,
    CSSPropertyGlyphOrientationHorizontal = 406,
    CSSPropertyGlyphOrientationVertical = 407,
    CSSPropertyKerning = 408,
    CSSPropertyTextAnchor = 409,
    CSSPropertyVectorEffect = 410,
    CSSPropertyWritingMode = 411,
    CSSPropertyPaintOrder = 412,
};

const int firstCSSProperty = 1;
const int numCSSProperties = 412;
const int lastCSSProperty = 412;
const size_t maxCSSPropertyNameLength = 34;

const char* getPropertyName(CSSPropertyID);
const WTF::AtomicString& getPropertyNameAtomicString(CSSPropertyID);
WTF::String getPropertyNameString(CSSPropertyID);
WTF::String getJSPropertyName(CSSPropertyID);
bool isInternalProperty(CSSPropertyID id);

inline CSSPropertyID convertToCSSPropertyID(int value)
{
    ASSERT((value >= firstCSSProperty && value <= lastCSSProperty) || value == CSSPropertyInvalid);
    return static_cast<CSSPropertyID>(value);
}

} // namespace WebCore

namespace WTF {
template<> struct DefaultHash<WebCore::CSSPropertyID> { typedef IntHash<unsigned> Hash; };
template<> struct HashTraits<WebCore::CSSPropertyID> : GenericHashTraits<WebCore::CSSPropertyID> {
    static const bool emptyValueIsZero = true;
    static const bool needsDestruction = false;
    static void constructDeletedValue(WebCore::CSSPropertyID& slot) { slot = static_cast<WebCore::CSSPropertyID>(WebCore::lastCSSProperty + 1); }
    static bool isDeletedValue(WebCore::CSSPropertyID value) { return value == (WebCore::lastCSSProperty + 1); }
};
}

#endif // CSSPropertyNames_h
