/*
 * Copyright (C) 2006, 2007, 2008, 2009, 2010 Apple Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 *
 */

#ifndef RefCounted_h
#define RefCounted_h

#include "Noncopyable.h"

namespace WTF {

// This base class holds the non-template methods and attributes.
// The RefCounted class inherits from it reducing the template bloat
// generated by the compiler (technique called template hoisting).
class RefCountedBase {
public:
    void ref()
    {
        ++m_refCount;
    }

    bool hasOneRef() const
    {
        return m_refCount == 1;
    }

    int refCount() const
    {
        return m_refCount;
    }

    void relaxAdoptionRequirement()
    {
    }

protected:
    RefCountedBase()
        : m_refCount(1)

    {
    }

    ~RefCountedBase()
    {
    }

    // Returns whether the pointer should be freed or not.
    bool derefBase()
    {
        if (m_refCount == 1) {
            return true;
        }
        --m_refCount;
        return false;
    }

private:

    int m_refCount;


};


template<typename T> class RefCounted : public RefCountedBase
{
    WTF_MAKE_NONCOPYABLE(RefCounted);

public:
    void deref()
    {
        if (derefBase())
            delete static_cast<T*>(this);
    }

protected:

    RefCounted()
    {
    }
};

} // namespace WTF

using WTF::RefCounted;

#endif // RefCounted_h
